name: Meu Primeiro workflow no gitHub Actions

on:
  push:
    branches: [ "main" ]

jobs:
  test_job:
    name: Executando o Job de Teste
    runs-on: ubuntu-latest    
    steps:
      - name: Sep 1  
        uses: actions/checkout@v3
      
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: 'paulovasconcelos88'
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          tags: 'paulovasconcelos88/fiap-estudogithubaction:latest'
          push: true
